/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desafio6;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class SelectorLenguajes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SelectorLenguajes.class.getName());

    /**
     * Creates new form SelectorLenguajes
     */
    public SelectorLenguajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaLenguajes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaLenguajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Java", "Python ", "C++ ", "JavaScript", "PHP" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaLenguajes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaLenguajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaLenguajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaLenguajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaLenguajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaLenguajesMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {  
        String lenguaje = listaLenguajes.getSelectedValue();

        if (lenguaje == null) return;

        String info = "";

        switch (lenguaje) {
            case "Java":
                info = "Java: Orientado a objetos, es el lenguaje mas usado en backend.";
                break;
            case "Python":
                info = "Python: Fácil de aprender, ideal para IA, análisis de datos y scripting.";
                break;
            case "C++":
                info = "C++: Lenguaje de alto rendimiento, usado en videojuegos y sistemas.";
                break;
            case "JavaScript":
                info = "JavaScript: base del desarrollo web.";
                break;
            case "PHP":
                info = "PHP: Popular en desarrollo web y sistemas como WordPress.";
                break;
        }

        JOptionPane.showMessageDialog(this, info);
        }
    }//GEN-LAST:event_listaLenguajesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SelectorLenguajes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaLenguajes;
    // End of variables declaration//GEN-END:variables
}
